source "https://rubygems.org"
ruby "2.4.1"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "rails", "~> 5.1.4"
gem "pg", "~> 0.18" 
gem "puma", "~> 3.7"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "turbolinks", "~> 5"
gem "awesome_print"
gem "slim"
gem "jquery-rails"
gem "bootstrap"
gem 'kaminari'
gem "devise"

gem "byebug"
gem 'activerecord-import', '~> 0.15.0'
gem 'materialize-sass', '~> 1.0.0'
gem 'material_icons'
gem 'client_side_validations'
gem 'html2slim'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'serviceworker-rails'
gem 'bonsai-elasticsearch-rails'


group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "capybara", "~> 2.13"
  gem "selenium-webdriver"
  gem "rspec-rails"
  gem "factory_girl"
  gem "database_cleaner"
  gem "faker", "~> 1.8"
end

group :development do
  gem "web-console", ">= 3.3.0"
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
